language: ruby
rvm:
  - 2.0
  - 2.1
notifications:
  email:
    recipients:
      - mattjones@yieldbot.com
    on_success: change
    on_failure: always

script:
  - 'bundle exec rake rubocop'
  - 'bundle exec rake spec'
